# Generated by Django 3.2.18 on 2023-02-21 15:18

import core.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(validators=[core.util.validate_deadline]),
        ),
    ]
